// Generated by gencpp from file behavior_tree_core/BTGoal.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_CORE_MESSAGE_BTGOAL_H
#define BEHAVIOR_TREE_CORE_MESSAGE_BTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree_core
{
template <class ContainerAllocator>
struct BTGoal_
{
  typedef BTGoal_<ContainerAllocator> Type;

  BTGoal_()
    : parameter(0)  {
    }
  BTGoal_(const ContainerAllocator& _alloc)
    : parameter(0)  {
  (void)_alloc;
    }



   typedef int32_t _parameter_type;
  _parameter_type parameter;





  typedef boost::shared_ptr< ::behavior_tree_core::BTGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree_core::BTGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BTGoal_

typedef ::behavior_tree_core::BTGoal_<std::allocator<void> > BTGoal;

typedef boost::shared_ptr< ::behavior_tree_core::BTGoal > BTGoalPtr;
typedef boost::shared_ptr< ::behavior_tree_core::BTGoal const> BTGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree_core::BTGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree_core::BTGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree_core::BTGoal_<ContainerAllocator1> & lhs, const ::behavior_tree_core::BTGoal_<ContainerAllocator2> & rhs)
{
  return lhs.parameter == rhs.parameter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree_core::BTGoal_<ContainerAllocator1> & lhs, const ::behavior_tree_core::BTGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree_core::BTGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree_core::BTGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree_core::BTGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b5e34835331aac7a9065c5abd204e3b";
  }

  static const char* value(const ::behavior_tree_core::BTGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b5e34835331aac7ULL;
  static const uint64_t static_value2 = 0xa9065c5abd204e3bULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree_core/BTGoal";
  }

  static const char* value(const ::behavior_tree_core::BTGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"int32 parameter #no goal needed for BT tick. But It could be useful to have a parameter for action (e.g.goto x,y)\n"
;
  }

  static const char* value(const ::behavior_tree_core::BTGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parameter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BTGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree_core::BTGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree_core::BTGoal_<ContainerAllocator>& v)
  {
    s << indent << "parameter: ";
    Printer<int32_t>::stream(s, indent + "  ", v.parameter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_CORE_MESSAGE_BTGOAL_H
